import Head from "next/head"
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai"
import { BsFillMoonStarsFill } from "react-icons/bs"
import { useState } from "react"

import deved from "../public/my-photo.jpg"
import Image from "next/image"

export default function Home() {
    const [darkMode, setDarkMode] = useState(false)

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>John Cor Baylen | Front-end Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/computer.png" />
            </Head>
            <section className="bg-white p-7 dark:bg-gray-900 border-b-2 border-b-gray sticky top-0">
                <nav className="flex justify-between dark:text-white">
                    <h1 className="font-burtons font-black text-xl">John Cor Baylen</h1>
                    <ul className="flex space-x-8 font-semibold ">
                        <li>
                            Home
                        </li>
                        <li>About</li>
                        <li>Projects</li>
                        <li>Contact</li>
                        <li>
                            <a
                                className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                                href="John-Cor-Baylen_Resume.docx"
                                download="John-Cor-Baylen_Resume"
                            >
                                Resume
                            </a>
                        </li>
                        <li>
                            <BsFillMoonStarsFill
                                onClick={() => setDarkMode(!darkMode)}
                                className=" cursor-pointer text-2xl"
                            />
                        </li>
                    </ul>
                </nav>
            </section>
            <main className=" bg-white px-10 pt-10 dark:bg-gray-900 md:px-20 lg:px-40">
                <section className="flex justify-center items-center ">
                    <div className=" inline-flex justify-center items-center">
                        <div className="text-center">
                            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
                                Front-End Developer 
                            </h2>
                            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                                Hi, I am John Cor Baylen. A passionate Front-end Developer based in Malabon, Metropolitan Manila, Philippines.
                            </p>
                            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                                <a 
                                    href="https://linkedin.com/in/john-cor-baylen-a673b6280/" 
                                    rel="noopener noreferrer" 
                                    target="_blank"
                                >
                                    <AiFillLinkedin />  
                                </a>    
                                <a 
                                    href="https://github.com/JohnCorBaylen" 
                                    rel="noopener noreferrer" 
                                    target="_blank"
                                >
                                    <AiFillGithub />
                                </a>
                            </div>
                        </div>
                        <div className="p-10">
                            <div className="rounded-full w-80 h-80 relative overflow-hidden md:h-96 md:w-96">
                                <Image 
                                src={deved} 
                                layout="fill" 
                                objectFit="cover" 
                                alt="" 
                            />
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    )
}
